services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.479.2-1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
    driver: local
  jenkins-docker-certs:
    driver: local